apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: example-nginx
  template:
    metadata:
      labels:
        run: example-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
